export type Permission = string; // e.g., "attendance.read", "payroll.export"

export const roleToPermissionPatterns: Record<string, string[]> = {
  ADMIN: [
    "*",
    "admin.read",
    "admin.tenant.read",
    "admin.access.read",
    "admin.integrations.read",
    "admin.audit.read",
    "admin.security.read",
    "reports.*",
    "analytics.*",
  ],

  MANAGEMENT: [
    "portal.announcements.read",
    "employees.directory.read",
    "employees.analytics.read",
    "employees.read",
    "leave.reports.read",
    "attendance.reports.read",
    "performance.cycles.read",
    "performance.reviews.read",
    "projects.*",
    "timesheets.*.read",
    "timesheets.export.*",
    "hiring.*",
    "hiring.dashboard.read",
    "hiring.requisitions.read",
    "applications.*",
    "applications.pipeline.read",
    "applications.submissions.*",
    "jds.*",
    "jds.create",
    "jds.read",
    "jds.approve.management",
    "jds.reports.read",
    "candidates.*",
    "resumes.*",
    "ownership.*",
    "finance.payroll.read",
    "finance.reports.read",
    "crm.*",
    "crm.integrations.read",
    "crm.demo.read",
    "crm.kpis.read",
    "reports.*",
    "analytics.*",
  ],

  VIEWER: [
    "portal.announcements.read",
    "employees.directory.read",
    "employees.read", // server will redacted PII where needed
    "leave.reports.read",
    "attendance.reports.read",
    "projects.*.read",
    "hiring.requisitions.read",
    "applications.pipeline.read",
    "applications.submissions.*",
    "finance.reports.read", // no exports, no bank files
  ],

  EMPLOYEE: [
    "portal.announcements.read",
    "attendance.read",
    "attendance.clock_in",
    "attendance.logs.read",
    "leave.requests.*",
    "leave.balance.read",
    "leave.requests.read",
    "timesheets.read",
    "timesheets.submit",
    "expenses.read",
    "expenses.submit",
    "finance.payslips.read",
    "finance.payslips.download",
    "finance.tax_declarations.read",
    "finance.investment_planner.read",
    "performance.goals.*",
    "performance.feedback_requests.*",
    "learning.read",
    "recognition.read",
    "ijp.postings.read",
    "ijp.applications.create",
    "helpdesk.tickets.read_own",
    "helpdesk.tickets.create",
  ],

  MANAGER: [
    "portal.announcements.read",

    // My Team module - Team management
    "team.management.read",
    "team.leave.read",
    "team.attendance.read",
    "team.timesheets.read",
    "team.expenses.read",
    "team.performance.read",
    "team.recognition.read",
    "team.learning.read",
    "team.profile_changes.read",
    "team.ijp.read",

    // Me module - Personal permissions
    "attendance.read",
    "attendance.clock_in",
    "attendance.team.read",
    "attendance.approvals.*",
    "leave.requests.*",
    "leave.balance.read",
    "leave.team.calendar.read",
    "leave.approvals.*",
    "timesheets.read",
    "timesheets.approvals.*",
    "finance.payslips.read",
    "finance.tax_declarations.read",
    "finance.investment_planner.read",
    "finance.audit_logs.read",
    "performance.goals.*",
    "performance.feedback_requests.*",
    "performance.reviews.create",
    "performance.meetings.*",
    "ijp.postings.read",
    "ijp.applications.read_team",
    "ijp.applications.approve",
    "ijp.applications.create",
    "helpdesk.tickets.read_own",
    "helpdesk.tickets.create",
  ],

  RECRUITER: [
    "portal.announcements.read",
    // Hiring module - Full access (keep wildcards)
    "hiring.*",
    "applications.*",
    "hiring.read",
    "hiring.dashboard.read",
    "hiring.jds.read",
    "hiring.candidates.read",
    "hiring.applications.read",
    "hiring.pipeline.read",
    "hiring.followup.read",
    "hiring.requisitions.read",
    "hiring.requisitions.create",
    "hiring.settings.read",
    "applications.submissions.*",
    "applications.pipeline.read",
    "interviews.schedule.*",
    "bgv.cases.create",
    "bgv.cases.read",
    "jds.create",
    "jds.bulk_import",
    "jds.smart_import",
    "candidates.create",
    "resumes.create",
    "applications.rank",
    "email.campaigns.send",
    "ownership.assign",
    "mapping.propose",
    // Me module - SPECIFIC permissions only (NO wildcards to avoid matching other modules)
    "attendance.read",
    "attendance.clock_in",
    "attendance.logs.read",
    "leave.requests.read",
    "leave.requests.create",
    "leave.requests.update",
    "leave.balance.read",
    "timesheets.read",
    "timesheets.submit",
    "expenses.read",
    "expenses.submit",
    "finance.payslips.read",
    "finance.payslips.download",
    "finance.tax_declarations.read",
    "finance.investment_planner.read",
    "performance.goals.read",
    "performance.goals.create",
    "performance.goals.update",
    "performance.feedback_requests.read",
    "performance.feedback_requests.create",
    "learning.read",
    "recognition.read",
    "ijp.postings.read",
    "ijp.applications.create",
    "helpdesk.tickets.read_own",
    "helpdesk.tickets.create",
  ],

  HIRING_MANAGER: [
    "portal.announcements.read",

    // Me module - Personal permissions
    "attendance.read",
    "attendance.clock_in",
    "attendance.logs.read",
    "leave.requests.read",
    "leave.requests.create",
    "leave.requests.update",
    "leave.balance.read",
    "timesheets.read",
    "timesheets.submit",
    "expenses.read",
    "expenses.submit",
    "finance.payslips.read",
    "finance.payslips.download",
    "finance.tax_declarations.read",
    "finance.investment_planner.read",
    "performance.goals.read",
    "performance.goals.create",
    "performance.goals.update",
    "performance.feedback_requests.read",
    "performance.feedback_requests.create",
    "learning.read",
    "recognition.read",
    "ijp.postings.read",
    "ijp.applications.create",
    "helpdesk.tickets.read_own",
    "helpdesk.tickets.create",

    // My Team module - Team management
    "team.dashboard.read",
    "team.management.read",
    "team.leave.read",
    "team.attendance.read",
    "team.timesheets.read",
    "team.expenses.read",
    "team.performance.read",
    "team.recognition.read",
    "team.learning.read",
    "team.profile_changes.read",
    "team.ijp.read",
    "leave.approvals.*",
    "timesheets.approvals.*",
    "attendance.approvals.*",
    "performance.reviews.create",
    "performance.meetings.*",

    // Hiring module - Full access
    "hiring.*",
    "applications.*",
    "hiring.read",
    "hiring.dashboard.read",
    "hiring.jds.read",
    "hiring.approvals.read",
    "hiring.candidates.read",
    "hiring.ownership.read",
    "hiring.applications.read",
    "hiring.pipeline.read",
    "hiring.followup.read",
    "hiring.settings.read",
    "hiring.settings.*",
    "hiring.requisitions.approve",
    "hiring.requisitions.read",
    "applications.pipeline.read",
    "applications.submissions.*",
    "offers.create",
    "offers.approve",
    "bgv.cases.read",
    "candidates.sensitive.read",
    "candidates.create",
    "resumes.create",
    "applications.rank",
    "ownership.assign",
    "mapping.propose",
    "jds.create",

    // HR module - Full access
    "hr.*",
    "hr.read",
    "hr.performance.read",
    "hr.leave.read",
    "hr.attendance.read",
    "hr.recognition.read",
    "hr.expenses.read",
    "hr.learning.read",
    "hr.ijp.read",
    "hr.helpdesk.read",
    "hr.onboarding.read",
    "hr.reports.read",
    "employees.*",
    "employees.directory.read",
    "onboarding.*",
    "offboarding.*",
    "policy.*",
    "letters.*",
    "bgv.*",

    // Projects module - Full access
    "projects.*",
    "projects.manage",
    "projects.dashboard.read",
    "projects.clients.read",
    "projects.projects.read",
    "projects.assignments.read",
    "projects.tasks.read",
    "projects.bench.read",
    "bench.*",

    // Org module - Read access
    "org.manage",
    "org.structure.read",
    "org.policies.read",

    // CRM read access
    "crm.read",
    "crm.clients.read",
    "crm.projects.read",
  ],

  STAFFING_MANAGER: [
    "portal.announcements.read",

    // Me module - Personal permissions
    "attendance.read",
    "attendance.clock_in",
    "attendance.logs.read",
    "leave.requests.*",
    "leave.balance.read",
    "leave.requests.read",
    "timesheets.read",
    "timesheets.submit",
    "expenses.read",
    "expenses.submit",
    "finance.payslips.read",
    "finance.payslips.download",
    "finance.tax_declarations.read",
    "finance.investment_planner.read",
    "performance.goals.*",
    "performance.feedback_requests.*",
    "learning.read",
    "recognition.read",
    "ijp.postings.read",
    "ijp.applications.create",
    "helpdesk.tickets.read_own",
    "helpdesk.tickets.create",

    // My Team module - Team management permissions
    "team.management.read",
    "team.leave.read",
    "team.attendance.read",
    "team.timesheets.read",
    "team.expenses.read",
    "team.performance.read",
    "team.recognition.read",
    "team.learning.read",
    "team.profile_changes.read",
    "team.ijp.read",
    "leave.approvals.*",
    "attendance.approvals.*",
    "timesheets.approvals.*",

    // Hiring module - Full access
    "hiring.*",
    "hiring.dashboard.read",
    "hiring.requisitions.read",
    "hiring.settings.*",
    "jds.*",
    "jds.create",
    "jds.read",
    "jds.approve.external",
    "candidates.*",
    "resumes.*",
    "applications.*",
    "applications.pipeline.read",
    "applications.submissions.*",
    "applications.rank",
    "mapping.approve",
  ],

  PROJECT_LEAD: [
    "portal.announcements.read",

    // Me module - Personal permissions
    "attendance.read",
    "attendance.clock_in",
    "attendance.logs.read",
    "leave.requests.*",
    "leave.balance.read",
    "leave.requests.read",
    "timesheets.read",
    "timesheets.submit",
    "expenses.read",
    "expenses.submit",
    "finance.payslips.read",
    "finance.payslips.download",
    "finance.tax_declarations.read",
    "finance.investment_planner.read",
    "performance.goals.*",
    "performance.feedback_requests.*",
    "learning.read",
    "recognition.read",
    "ijp.postings.read",
    "ijp.applications.create",
    "helpdesk.tickets.read_own",
    "helpdesk.tickets.create",

    // My Team module - Team management permissions
    "team.management.read",
    "team.leave.read",
    "team.attendance.read",
    "team.timesheets.read",
    "team.expenses.read",
    "team.performance.read",
    "team.recognition.read",
    "team.learning.read",
    "team.profile_changes.read",
    "team.ijp.read",
    "leave.approvals.*",
    "attendance.approvals.*",
    "timesheets.approvals.*",
  ],

  DELIVERY_HEAD: [
    "portal.announcements.read",

    // Me module - Personal permissions
    "attendance.read",
    "attendance.clock_in",
    "attendance.logs.read",
    "leave.requests.*",
    "leave.balance.read",
    "leave.requests.read",
    "timesheets.read",
    "timesheets.submit",
    "expenses.read",
    "expenses.submit",
    "finance.payslips.read",
    "finance.payslips.download",
    "finance.tax_declarations.read",
    "finance.investment_planner.read",
    "performance.goals.*",
    "performance.feedback_requests.*",
    "learning.read",
    "recognition.read",
    "ijp.postings.read",
    "ijp.applications.create",
    "helpdesk.tickets.read_own",
    "helpdesk.tickets.create",

    // My Team module - Team management permissions
    "team.management.read",
    "team.leave.read",
    "team.attendance.read",
    "team.timesheets.read",
    "team.expenses.read",
    "team.performance.read",
    "team.recognition.read",
    "team.learning.read",
    "team.profile_changes.read",
    "team.ijp.read",
    "leave.approvals.*",
    "attendance.approvals.*",
    "timesheets.approvals.*",

    // Hiring module - Full access
    "hiring.*",
    "hiring.requisitions.*",
    "hiring.candidates.*",
    "hiring.interviews.*",
    "hiring.offers.*",
    "hiring.pipeline.*",
    "hiring.reports.*",

    // Projects module - Full access
    "projects.read",
    "projects.assignments.read",
    "projects.tasks.read",
    "projects.bench.read",
    "projects.reports.read",

    // CRM module - Full access
    "crm.read","crm.clients.read","crm.accounts.read","crm.projects.read",
    "crm.opportunities.read","crm.interactions.read","crm.dashboard.read",
    "crm.reports.read","crm.analytics.read",
    "contracts.read","contracts.msa.read","contracts.sow.read","contracts.po.read",

    // Management module - Full access
    "ownership.*",
    "management.*",
    "management.dashboard.read",
    "management.reports.read",

    // Reports module - Full access
    "reports.*",
    "reports.read",
    "reports.create",
    "reports.schedule",

    // Analytics module - Full access
    "analytics.*",
    "analytics.read",
    "analytics.advanced",
    "analytics.projections",
  ],

  HR_LEAD: [
    "portal.announcements.read",

    // Me module - Personal permissions
    "attendance.read",
    "attendance.clock_in",
    "attendance.logs.read",
    "leave.requests.*",
    "leave.balance.read",
    "leave.requests.read",
    "timesheets.read",
    "timesheets.submit",
    "expenses.read",
    "expenses.submit",
    "finance.payslips.read",
    "finance.payslips.download",
    "finance.tax_declarations.read",
    "finance.investment_planner.read",
    "performance.goals.*",
    "performance.feedback_requests.*",
    "learning.read",
    "recognition.read",
    "ijp.postings.read",
    "ijp.applications.create",
    "helpdesk.tickets.read_own",
    "helpdesk.tickets.create",

    // My Team module - Team management
    "team.dashboard.read",
    "team.management.read",
    "team.leave.read",
    "team.attendance.read",
    "team.timesheets.read",
    "team.expenses.read",
    "team.performance.read",
    "team.recognition.read",
    "team.learning.read",
    "team.profile_changes.read",
    "team.ijp.read",
    "leave.approvals.*",
    "timesheets.approvals.*",
    "attendance.approvals.*",
    "performance.reviews.create",
    "performance.meetings.*",

    // Org module - Full access
    "org.manage",
    "org.structure.read",
    "org.policies.read",
    "employees.directory.read",
    "employees.read",
    "employees.letters.create",

    // HR module - Full access
    "hr.*",
    "hr.read",
    "hr.performance.read",
    "hr.leave.read",
    "hr.attendance.read",
    "hr.recognition.read",
    "hr.expenses.read",
    "hr.learning.read",
    "hr.ijp.read",
    "hr.helpdesk.read",
    "hr.onboarding.read",
    "hr.reports.read",
    "employees.*",
    "onboarding.*",
    "offboarding.*",
    "policy.*",
    "letters.*",
    "leave.adjustments.update",
    "attendance.adjustments.update",
  ],

  HR_MANAGER: [
    "portal.announcements.read",

    // HR module - Full access
    "hr.*",
    "hr.read",
    "hr.performance.read",
    "hr.leave.read",
    "hr.attendance.read",
    "hr.recognition.read",
    "hr.expenses.read",
    "hr.learning.read",
    "hr.ijp.read",
    "hr.helpdesk.read",
    "hr.onboarding.read",
    "hr.reports.read",
    "employees.*",
    "employees.directory.read",
    "onboarding.*",
    "offboarding.*",
    "policy.*",
    "letters.*",
    "bgv.*",
    "payroll.runs.read",
    "jds.approve.internal",
    "jds.publish",
    "candidates.*",
    "resumes.*",

    // Hiring module - Full access
    "hiring.*",
    "applications.*",
    "hiring.read",
    "hiring.dashboard.read",
    "hiring.jds.read",
    "hiring.approvals.read",
    "hiring.candidates.read",
    "hiring.ownership.read",
    "hiring.applications.read",
    "hiring.pipeline.read",
    "hiring.followup.read",
    "hiring.settings.read",
    "hiring.settings.*",
    "hiring.requisitions.approve",
    "hiring.requisitions.read",
    "applications.pipeline.read",
    "applications.submissions.*",
    "offers.create",
    "offers.approve",
    "bgv.cases.read",
    "candidates.sensitive.read",
    "candidates.create",
    "resumes.create",
    "applications.rank",
    // SPECIFIC ownership permissions (not ownership.*)
    "ownership.assign",
    "ownership.transfer",
    "ownership.read",
    "mapping.propose",
    "jds.create",

    // My Team module - SPECIFIC permissions (not team.*)
    "team.dashboard.read",
    "team.management.read",
    "team.leave.read",
    "team.attendance.read",
    "team.timesheets.read",
    "team.expenses.read",
    "team.performance.read",
    "team.recognition.read",
    "team.learning.read",
    "team.profile_changes.read",
    "team.ijp.read",
    "leave.approvals.*",
    "timesheets.approvals.*",
    "attendance.approvals.*",
    "performance.reviews.create",
    "performance.meetings.*",

    // Org module - Full access
    "org.manage",
    "org.structure.read",
    "org.policies.read",

    // Me module - SPECIFIC permissions
    "attendance.read",
    "attendance.clock_in",
    "attendance.logs.read",
    "leave.requests.read",
    "leave.requests.create",
    "leave.requests.update",
    "leave.balance.read",
    "timesheets.read",
    "timesheets.submit",
    "expenses.read",
    "expenses.submit",
    "finance.payslips.read",
    "finance.payslips.download",
    "finance.tax_declarations.read",
    "finance.investment_planner.read",
    "finance.audit_logs.read",
    "performance.goals.read",
    "performance.goals.create",
    "performance.goals.update",
    "performance.feedback_requests.read",
    "performance.feedback_requests.create",
    "learning.read",
    "recognition.read",
    "ijp.*",
    "ijp.postings.read",
    "ijp.applications.create",
    "helpdesk.tickets.read_own",
    "helpdesk.tickets.create",
  ],

  PAYROLL_SPECIALIST: [
    "portal.announcements.read",
    "payroll.runs.read",
    "payroll.runs.create",
    "payroll.runs.approve",
    "payroll.bank_file.generate",
    "payroll.statutory.generate",
    "finance.payslips.generate",
    "finance.payroll.read",
  ],

  FINANCE_ANALYST: [
    "portal.announcements.read",
    "finance.read",
    "finance.payroll.read",
    "finance.reports.read",
    "finance.jv.export",
    "finance.audit_logs.read",
    "payroll.runs.read",
    "employees.read",
    "employees.directory.read",
  ],

  FINANCE_MANAGER: [
    "portal.announcements.read",

    // Me module - Personal permissions
    "attendance.read",
    "attendance.clock_in",
    "attendance.logs.read",
    "leave.requests.*",
    "leave.balance.read",
    "leave.requests.read",
    "timesheets.read",
    "timesheets.submit",
    "expenses.read",
    "expenses.submit",
    "finance.payslips.read",
    "finance.payslips.download",
    "finance.tax_declarations.read",
    "finance.investment_planner.read",
    "performance.goals.*",
    "performance.feedback_requests.*",
    "learning.read",
    "recognition.read",
    "ijp.postings.read",
    "ijp.applications.create",
    "helpdesk.tickets.read_own",
    "helpdesk.tickets.create",

    // My Team module - Team management
    "team.dashboard.read",
    "team.management.read",
    "team.leave.read",
    "team.attendance.read",
    "team.timesheets.read",
    "team.expenses.read",
    "team.performance.read",
    "team.recognition.read",
    "team.learning.read",
    "team.profile_changes.read",
    "team.ijp.read",
    "leave.approvals.*",
    "timesheets.approvals.*",
    "attendance.approvals.*",
    "performance.reviews.create",
    "performance.meetings.*",

    // Org module - Full access
    "org.manage",
    "org.structure.read",
    "org.policies.read",
    "employees.directory.read",
    "employees.read",

    // Finance module - Full access
    "finance.*",
    "finance.read",
    "finance.reports.read",
    "finance.payroll.read",
    "finance.invoices.*",
    "finance.jv.export",
    "finance.audit_logs.read",
    "payroll.*",
    "payroll.runs.read",
    "payroll.runs.create",
    "payroll.runs.approve",
    "payroll.bank_file.generate",
    "payroll.statutory.generate",
    "finance.payslips.generate",
    "contracts.*",
  ],

  IT_HELPDESK: [
    "portal.announcements.read",
    "it.read",
    "it.helpdesk.read",
    "helpdesk.dashboard.read",
    "helpdesk.tickets.read_queue",
    "helpdesk.tickets.assign",
    "helpdesk.tickets.update_status",
  ],
  INTERN: [
    // Portal - Home module
    "portal.announcements.read",

    // Me module - Personal permissions (same as EMPLOYEE)
    "attendance.read",
    "attendance.clock_in",
    "attendance.logs.read",
    "leave.requests.*",
    "leave.balance.read",
    "leave.requests.read",
    "timesheets.read",
    "timesheets.submit",
    "expenses.read",
    "expenses.submit",
    "finance.payslips.read",
    "finance.payslips.download",
    "finance.tax_declarations.read",
    "finance.investment_planner.read",
    "performance.goals.*",
    "performance.feedback_requests.*",
    "learning.read",
    "recognition.read",
    "ijp.postings.read",
    "ijp.applications.create",
    "helpdesk.tickets.read_own",
    "helpdesk.tickets.create",

    // Org module - Read access
    "org.structure.read",
    "org.policies.read",
    "employees.read",
    "employees.directory.read",
  ],

  AUDITOR_RO: [
    "portal.announcements.read",
    "employees.read",
    "leave.reports.read",
    "attendance.reports.read",
    "finance.reports.read",
    "payroll.runs.read",
  ],

  DPO_PRIVACY: [
    "portal.announcements.read",
    "privacy.dsr.read",
    "privacy.dsr.fulfill",
    "employees.pii.view",
    "employees.pii.export",
  ],

  OPERATIONS_HR: [
    // Employee base permissions
    "portal.announcements.read",
    "employees.read",
    "org.structure.read",
    "org.policies.read",
    "attendance.read",
    "attendance.clock_in",
    "attendance.logs.read",
    "leave.requests.*",
    "leave.balance.read",
    "leave.requests.read",
    "timesheets.read",
    "timesheets.submit",
    "expenses.read",
    "expenses.submit",
    "finance.payslips.read",
    "finance.payslips.download",
    "finance.tax_declarations.read",
    "finance.investment_planner.read",
    "performance.goals.*",
    "performance.feedback_requests.*",
    "learning.read",
    "recognition.read",
    "ijp.postings.read",
    "ijp.applications.create",
    "helpdesk.tickets.read_own",
    "helpdesk.tickets.create",
    // CRM full access
    "crm.*",
    "crm.clients.*",
    "crm.accounts.*",
    "crm.projects.*",
    "crm.spocs.*",
    "crm.interactions.*",
    "crm.opportunities.*",
    "crm.documents.*",
    "crm.kpis.read",
    "contracts.*",
    // Org module
    "org.structure.read",
    "org.policies.read",
    "employees.read",
    "employees.directory.read",
    // Projects full access
    "projects.*",
    "projects.dashboard.read",
    "projects.clients.read",
    "projects.projects.read",
    "projects.assignments.read",
    "projects.tasks.read",
    "projects.bench.read",
    "projects.timesheets.read",
    // management full access
    "management.*",
  ],
};

export function matchPermission(patterns: string[], perm: Permission): boolean {
  if (patterns.includes("*")) return true;
  return patterns.some((p) => {
    if (p.endsWith(".*")) {
      const ns = p.slice(0, -2);
      return perm === ns || perm.startsWith(ns + ".");
    }
    return p === perm;
  });
}
