-- Insert sample JD approval records with jd_id
INSERT INTO jd_approvals (
  jd_id,
  project_name, 
  client_name, 
  headcount, 
  salary_band_min, 
  salary_band_max, 
  currency,
  cost_center,
  business_justification,
  current_step,
  created_by,
  submitted_at
) VALUES 
  (
    gen_random_uuid(),
    'Senior React Developer',
    'TechCorp Solutions',
    3,
    80000,
    120000,
    'USD',
    'Engineering-Frontend',
    'Need experienced React developers to build new customer portal and migrate legacy applications to modern tech stack.',
    1,
    '80e1c9ce-49f1-415e-84eb-3f78d9c6c0be',
    NOW() - INTERVAL '5 days'
  ),
  (
    gen_random_uuid(),
    'DevOps Engineer',
    'TechCorp Solutions',
    2,
    90000,
    130000,
    'USD',
    'Engineering-Infrastructure',
    'Expanding cloud infrastructure team to support growing customer base and new product launches.',
    2,
    '80e1c9ce-49f1-415e-84eb-3f78d9c6c0be',
    NOW() - INTERVAL '3 days'
  ),
  (
    gen_random_uuid(),
    'Product Manager',
    'IHCL',
    1,
    100000,
    140000,
    'USD',
    'Product-Management',
    'Strategic hire to lead new product line development and manage cross-functional teams.',
    0,
    '80e1c9ce-49f1-415e-84eb-3f78d9c6c0be',
    NULL
  ),
  (
    gen_random_uuid(),
    'UX Designer',
    'ConsultingEdge',
    2,
    70000,
    100000,
    'USD',
    'Design-UX',
    'Building design team to improve user experience across all client-facing products.',
    1,
    '80e1c9ce-49f1-415e-84eb-3f78d9c6c0be',
    NOW() - INTERVAL '7 days'
  ),
  (
    gen_random_uuid(),
    'Full Stack Engineer',
    'Global Finance Ltd',
    5,
    85000,
    125000,
    'USD',
    'Engineering-Full-Stack',
    'Major expansion of development team to build new financial platform and modernize existing systems.',
    3,
    '80e1c9ce-49f1-415e-84eb-3f78d9c6c0be',
    NOW() - INTERVAL '2 days'
  ),
  (
    gen_random_uuid(),
    'Data Scientist',
    'TechCorp Solutions',
    2,
    95000,
    135000,
    'USD',
    'Data-Analytics',
    'Establishing data science team to drive AI/ML initiatives and improve business intelligence.',
    1,
    '80e1c9ce-49f1-415e-84eb-3f78d9c6c0be',
    NOW() - INTERVAL '10 days'
  ),
  (
    gen_random_uuid(),
    'QA Automation Engineer',
    'IHCL',
    3,
    75000,
    105000,
    'USD',
    'Engineering-QA',
    'Strengthening quality assurance to support rapid product development and ensure high quality releases.',
    0,
    '80e1c9ce-49f1-415e-84eb-3f78d9c6c0be',
    NULL
  ),
  (
    gen_random_uuid(),
    'Backend Engineer',
    'ConsultingEdge',
    4,
    80000,
    115000,
    'USD',
    'Engineering-Backend',
    'Scaling backend infrastructure to handle increased load and implement new microservices architecture.',
    1,
    '80e1c9ce-49f1-415e-84eb-3f78d9c6c0be',
    NOW() - INTERVAL '1 day'
  );