// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jflphinczkhzabmpwdok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmbHBoaW5jemtoemFibXB3ZG9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5OTc5NDIsImV4cCI6MjA3MjU3Mzk0Mn0.Rc1RIGgKnjXXZVfUgV3hrROE878_1_XN770q7gf8xO4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});