name: Sync main → x2 dev_latest

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push main to x2 dev_latest
        env:
          THRTOKEN: ${{ secrets.THRTOKEN }}
        run: |
          git config --global user.email "sync@github-actions.com"
          git config --global user.name "x1-to-x2-sync"

          git push https://x2:${THRTOKEN}@github.com/techouts/Thrportal.git main:dev_latest --force
